menu:
- {name: 'Research', url: '/research'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}
# - {name: 'people', url: '/people'}
# - {name: 'courses', url: '/courses'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

research:
- {Subject: 'Ice Sheet-Sea Level interactions', Description: 'This page is still under construction! I research how ice sheets and sea level interact with each other', image: 'assets/img/fingerprint.jpg', alt: 'The sea level fingerprint associated with the melting of the West Antarctic Ice Sheet', url: 'sea-level'}
- {Subject: 'Ice Sheet-Climate interactions', Description: 'Ice sheets also affect climate', image: 'assets/img/lapse_and_albedo.jpg', alt: 'A figure illustrating the effects ice sheets have on their local climate through altering local elevation and albedo', url: 'climate'}
- {Subject: 'Machine Learning and emulation', Description: 'Models. They take so long to run. What if we emulate them instead?', image: 'assets/img/GPR_math', alt: 'The math behind Gaussian process emulation', url: 'emulation'}
- {Subject: 'Dynamic topography', Description: 'Dynamic topography is important for long-term sea level rise', image: 'assets/img/richards2023_dynamic_topo', alt: 'A figure illustrating the present-day predicted dynamic topography signal', url: 'dynamic-topography'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/bparazin'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/bparazin/'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-3155-0385'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}

contacts:
- {name: 'B. Parazin', title: 'PhD Candidate', department: 'Earth & Planetary Science', institution: 'McGill University', institution_address: '3450 Rue University, Montr√©al, QC H3A 2A7', email: 'Bc.parazin@mail.mcgill.ca', office: 'Frank Dawson Adams 311', image: 'assets/img/Glacier_small.jpg'}
